default-remote: test
remotes:
    mynode1:
        host: 10.10.10.10
        port: 22
        protocol: tcp
        auth_type: password
        user: geaaru
        pass: pass
    mynode2:
        host: 192.168.0.90
        port: 22
        protocol: tcp
        auth_type: publickey
        privatekey_file: /home/geaaru/.ssh/id_ed25519
        user: geaaru
    test:
        host: 172.18.10.192
        port: 22
        protocol: tcp
        auth_type: password
        user: root
        pass: pass
    test2:
        host: 172.18.10.192
        port: 22
        protocol: tcp
        auth_type: password
        user: root
        pass: pass

    # Example of remote with hops:
    # mynode -> 192.168.0.10 -> 192.168.0.20 -> 172.18.10.190
    nodewithhops:
        # Example report a simple network create
        # with the LXD setup from Mottainai and the
        # mottainai0 network using 172.18.0.0/23 net.
        # Example: lxd-compose network create -a
        host: 172.18.10.190
        port: 22
        protocol: tcp
        auth_type: password
        user: root
        pass: pass
        # This option add local port binding
        # of the SSH session in order to reach
        # the final node. This option is optional
        # and used if you want use ssh and/or other
        # commands over SSH with different tools.
        tun_local_port: 20000
        tun_local_addr: "localhost"
        tun_local_bind: true
        chain:
          # First host/container node
          - host: 192.168.0.10
            port: 22
            auth_type: password
            user: root
            pass: pass

          # Second host/container node
          - host: 192.168.0.20
            port: 22
            auth_type: publickey
            user: root
            privatekey_file: ./mysecrets/ssh-key

